version: '3.9'
services:
  api:
    build: .
    environment:
      - PORT=3000
      - NODE_ENV=production
      - FORCE_HTTPS=false
      - ACTIVE_JWT_KID=default
      - JWT_KEYS_JSON={"default":"changeme_in_env"}
      - JWT_ISS=purple-team-app
      - JWT_AUD=purple-team-clients
      - MONGO_URI=mongodb://mongo:27017/purple_team?replicaSet=rs0
      - CORS_ORIGIN=http://localhost:3000
      - REDIS_URL=redis://redis:6379/0
      - MFA_ENFORCE_ADMIN=true
    depends_on:
      - mongo
      - redis
    ports:
      - "3000:3000"
  mongo:
    image: mongo:6
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    healthcheck:
      test: test $$(echo 'rs.initiate({_id:"rs0",members:[{_id:0,host:"mongo:27017"}]}).ok || rs.status().ok' | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
  redis:
    image: redis:7
    ports:
      - "6379:6379"
